### ISSUE TITLE
Fix problems in Rules ported from Java

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#11]
I ported nearly all code size related rules from the Java PMD (https://github.com/Up2Go/pmd/tree/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/codesize) module but many test fail.

There can be different root causes:

- Mapped the wrong Jorje nodes to the expected Java nodes
- Took out code as some nodes visited in Java don't exist in Apex
- XML Testdata needs to be adapted to look like Apex and match rules changes

@chalemic , @anand13s maybe you can help me shoot those bugs ;-)

**Comment by Up2Go-DavidRenz** [comment]
I just compared the trees of identical and simple Java and Apex classes:

![compare](https://cloud.githubusercontent.com/assets/8180433/14070531/2a079de8-f4a8-11e5-81f1-f87752cc3065.png)

These **clinit**, **clone** and **init** methods could cause the test fails.
@adangel mentioned them alreay here: https://github.com/Up2Go/pmd/pull/7

**Comment by up2go-rsoesemann** [comment]
@Up2Go-DavidRenz  Closed this as Duplicate of #1.
