### ISSUE TITLE
Rules don't visit child nodes

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#13]
@adangel I just realized that only those rule test succeed that expect not rule violation at all. Something which should work with no rule at all...

This looks more like a configuration or parser error at all...

I tried to debug the test for this rule https://github.com/Up2Go/pmd/blob/7be1510a65d7ab36c41c30f59029e55b8c3ae75b/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/basic/AvoidSoqlInLoopsRule.java#L20 but this line was never executed.

??? Andy idea?

**Comment by up2go-rsoesemann** [comment]
@adangel The problem might be how I integrated the Salesforce parser.

I tried to convert the [following lines of the Ecmascript module](https://github.com/Up2Go/pmd/blob/master/pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/EcmascriptParser.java#L37)

    AstRoot astRoot = parser.parse(sourceCode, sourceURI, beginLineno);
    parseProblems.addAll(errorCollector.getErrors());
    return astRoot;

to https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexParser.java#L34

    public UserClass parseApex(final String sourceCode) throws ParseException {
        TopLevelVisitor visitor = new TopLevelVisitor();
        CompilerService.INSTANCE.visitAstFromString(sourceCode, visitor);
        UserClass astRoot = visitor.getTopLevel();
        return astRoot;
     }

using this pseudo-visitor to get root node (this looks o damn wrong ;-). Could it be that using this construct I am ignoring or the children and their adapter visit methods?

     private class TopLevelVisitor extends AstVisitor<AdditionalPassScope> {
                UserClass topLevel;

		public UserClass getTopLevel() {
			return topLevel;
		}

		@Override
		public void visitEnd(UserClass node, AdditionalPassScope scope) {
			topLevel = node;
		}
	}

**Comment by adangel** [comment]
Using the TopLevel-Visitor is not the problem. The problem was in how we ended up with the visitor implementation in the AST nodes: the method jjtAccept has to be in each concrete subclass, otherwise java will call only the base visit method... more information here: http://stackoverflow.com/a/2794236/1169968

I've move the jjtAccept method into each AST node class and fixed the AvoidSoqlInLoopsRule.

**Comment by up2go-rsoesemann** [comment]
Puuh, I would have taken a while to find out that it was related to double dispatch and overloading.... Thanks @adangel for adding the jjtAccept to all classes. Is this the Visitor Accept Method off JavaCC and JJTree? or is ti a specific PMD interface?

**Comment by adangel** [comment]
Yes, this is the JJTree interface, that would be generated for javacc grammars.
