### ISSUE TITLE
Get absolute line numbers or block lengths in Jorje

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#14]
@vazexqi @anand13s 

I need you help getting line start and end numbers of a Method, class or field in this abstract Node class

https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/AbstractApexNode.java#L41

Many PMD rules that I ported need to know the lenght of a method or a class the decide wether a rule is violated or not.

**Comment by vazexqi** [comment]
Can you give some concrete examples or test cases with expected results? In particular, we need to know what do you mean by the length of a method? So far, we are just using the length of the identifier for the method to provide the position. I'm assuming, but you need to provide some test cases, that you actually want the starting position to be where the first modifier {public, global, etc} is until the closing parenthesis?

**Comment by up2go-rsoesemann** [comment]
Sure. Just look into this rule base class which is using `endline - startline` to get the length of a method:

https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/design/ExcessiveLengthRule.java#L30

In the Java PMD they already stripped comments out so the get a "real" length. I would need to know how to implement the methods used here using the Jorje parser:

https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/AbstractApexNode.java

**Comment by up2go-rsoesemann** [comment]
@adangel Maybe we need an approach like in the Javascript module where the Rhino parser also only gives relative line information

https://github.com/Up2Go/pmd/blob/master/pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/SourceCodePositioner.java

@vazexqi as far as I understand the RealLoc class of Jorje `line` tells in which line the node is located
and `startIndex` and `endIndex` refer to the nodes of the subtree.

By going `endIndex-startIndex` nodes from the current node and asking it for its `line` we would have the endLine of a method.

**Comment by up2go-rsoesemann** [comment]
Great @adangel. Thanks for fixing this. I will close this issue as this is good enough for the moment.
