### ISSUE TITLE
Parsing Apex classes with annotations like @isTest, @TestVisible and @deprecated

### ISSUE THREAD

**Issue by Up2Go-DavidRenz** [Up2Go/pmd#16]
Parsing Apex classes with annotations(**@isTest**, **@TestVisible**, **@deprecated**) fails with an UnsupportedOperationException at https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java#L218

@vazexqi @anand13s 
Any idea which node could be missing or cause the problem?

**Comment by up2go-rsoesemann** [comment]
Maybe @adangel can help understand this. I compared the AST classes of the java module with each other and found that all AST classes in java look equal to ours but only the ASTAnnotation has way more code. Is this something PMD specific or Java specific? Do we need special Root Node Annotation handling in our modules as well?

**Comment by up2go-rsoesemann** [comment]
Fixed with the help of @adangel
