### ISSUE TITLE
Best process for Salesforce community to contribute new rules

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#17]
@adangel What do you recommend for the future of our Apex module? How do Salesforce.com developers contribute enhancements (rules, bugfixes)?

Should we encourage them to fork the pmd/pmd repo and create direct pull-request to your repo or should we and our fork function as kind of quality gate where contributers have to pull-request back to our fork first.

**Comment by adangel** [comment]
Well, I think the goal is, to have your fork with pmd-apex merged back into the main pmd repo. This will make sure, that pmd-apex will be included in the usual releases of PMD.

As soon as the merge is done, contributions can be directly based on the pmd/pmd repo. Of course, any help from your side would be appreciated. If you want, I can give you access to the pmd/pmd repo and you can have an eye on the pmd-apex module.

Regarding merging: the main requirement is the Jorje parser lib - see also https://github.com/Up2Go/pmd/issues/18

**Comment by up2go-rsoesemann** [comment]
Please see comment regarding "merging requirement" in #18
