### ISSUE TITLE
Running Java on Docker? Are we Breaking the Law?!

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#21]
@mrb I just read this: [http://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/](http://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/).

Isn't running PMD inside a CodeClimate engine exactely that?

**Comment by up2go-rsoesemann** [comment]
<img width="769" alt="bildschirmfoto 2016-04-04 um 15 39 38" src="https://cloud.githubusercontent.com/assets/8180281/14249931/6d6c43ca-fa7c-11e5-8b85-2aed9e606c5d.png">

**Comment by mrb** [comment]
This isn't a problem as far as we're concerned.
