### ISSUE TITLE
java.lang.NoClassDefFoundError: apex/jorje/semantic/symbol/type/ModifierOrAnnotationTypeInfo

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#22]
@vazexqi To implement this rule we need to find out if a method uses the override keyword. We do this like this

https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/naming/MethodNamingConventionsRule.java#L34

Executing this rule fails with this error:

> Exception in thread "main" java.lang.NoClassDefFoundError: apex/jorje/semantic/symbol/type/ModifierOrAnnotationTypeInfo
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at net.sourceforge.pmd.RuleSetFactory.parseSingleRuleNode(RuleSetFactory.java:396)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleNode(RuleSetFactory.java:310)
	at net.sourceforge.pmd.RuleSetFactory.parseRuleSetNode(RuleSetFactory.java:261)

FYI: @adangel

**Comment by adangel** [comment]
Hm... ModifierOrAnnotationTypeInfo is a interface, not a class. Seems like, if you try to instantiate a interface via reflection, you'll get "NoClassDefFoundError".

Line 396 in RuleSetFactory does this - it instantiates it. It tries to instantiate the new Rule.

So, this looks like a typo in a ruleset.xml file, where the class-Attribute of one rule points to ModifierOrAnnotationTypeInfo and not to a rule...
I would double check the xml files here: https://github.com/Up2Go/pmd/tree/master/pmd-apex/src/main/resources/rulesets/apex
I searched for "ModifierOrAnnotationTypeInfo" but I don't see anything there...

@up2go-rsoesemann  When do you get this error? Which unit test? Do you have local changes?
At least this line: https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/resources/rulesets/apex/naming.xml#L36 looks correct in the repo....

**Comment by up2go-rsoesemann** [comment]
@adangel when I take out the rule in

https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/resources/rulesets/apex/naming.xml#L34

everything works fine (which is not a solution). I 90% sure that this is the problematic line of code

https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/rule/naming/MethodNamingConventionsRule.java#L34

Accessing modifiers like this leads to errors. But I didn't find out how else to get the info if there is an override. I hope to get the answer from @vazexqi  or @anand13s.

**Comment by up2go-rsoesemann** [comment]
@adangel @vazexqi As soon as I comment out the

import static apex.jorje.semantic.symbol.type.ModifierTypeInfos.OVERRIDE;

and

    private boolean isOverriddenMethod(ASTMethod node) {
        return node.getNode().getModifiers().has(OVERRIDE);
    }

the error goes away and a new one appears. Again a NoClassDefFound: 

> Exception in thread "main" java.lang.NoClassDefFoundError: apex/jorje/semantic/ast/AstNode
> 	at net.sourceforge.pmd.lang.apex.ApexParser.<init>(ApexParser.java:23)
> 	at net.sourceforge.pmd.lang.apex.ApexHandler.getParser(ApexHandler.java:47)
> 	at net.sourceforge.pmd.PMD.parserFor(PMD.java:125)
> 	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:136)
> 	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:76)
> 	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:43)
> 	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:79)
> 	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:1)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

**Comment by adangel** [comment]
Hm... I don't see the exception with the current code.
What do you start? And how do you start it? I ran the NamingRulesTest from within eclipse and didn't notice any exceptions in the console (and the tests for MethodNamingConventions are working).

**Comment by up2go-rsoesemann** [comment]
@adangel I try to run the CLI inside of Eclipse. Using a JRE 8 and those arguments

    -d /Users/robert/git/cprm-pm/src/classes -f codeclimate -R apex-ruleset  -l apex -v 35

Are you successful running the CLI?

**Comment by Up2Go-DavidRenz** [comment]
It seems this issue only occurs if you run the **CLI inside of eclipse**.
You should try it this way:

1. Build PMD with `mvn clean package` in the pmd top-level-directory 

2. Unzip the _pmd-bin-5.5.0-SNAPSHOT.zip_ archive found in _pmd-dist/target_

3. run `bin/run.sh pmd -d /directory/of/your/apex/src/files -f codeclimate -R apex-ruleset` in the unziped directory

In my case I have to disable the _UseUtilityClass_ rule in DesignRulesTest of the Java modul in order to build PMD.
