### ISSUE TITLE
How to integrate with Code Climate (Apex-only or full PMD)

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#27]
@mrb I just came to the conclusion that it would be stupid to reduce the scope and audience of the Code Climate engine we plan to build from our PMD extension to just an Apex engine. So I renamed the upcoming repo for it to https://github.com/Up2Go/codeclimate-pmd.

As soon as our trunk gets merged into the [pmd main repo](https://github.com/pmd/pmd) by @adangel (planned for this or next week) our module and rules are part of the regular PMD distributions (e.g. containing an Eclipse plugin for static code analysis).

Given the fact that many people are asking for a Java engine on Code Climate why not configure our engine so it can analyze ALL files PMD can handle?

@adangel: Can you confirm that there is a way to call the CLI without telling it the language of the files. Looking at the code it will check all files for known file extension and then apply all available rules to them.

So this project would be Win-Win for both PMD (getting into the cloud and closer to Github) and Code Climate (officially support Java).

**Comment by mrb** [comment]
@up2go-rsoesemann We should definitely chat about this on Skype, I like the direction you're going with it. /c @jpignata

**Comment by up2go-rsoesemann** [comment]
Sure @mrb. Just ping me when you are awake and have time.

**Comment by up2go-rsoesemann** [comment]
@mrb and @jpignata I made you outside collaborators on this repo and the [still empty `Up2Go/codeclimate-pmd` repo](https://github.com/Up2Go/codeclimate-pmd) just in case you already want to work on some integration code ;-)

As discussed we will contact you when we have this fork merged back into [`pmd/pmd`](https://github.com/Up2Go/codeclimate-pmd).

**Comment by up2go-rsoesemann** [comment]
@mrb we finalized version 1.0 today and will pull request. So we should have the planned next steps meeting with you next week. Could you please send an invitation instead of myself as I think you are way more busy than us ;-)

**Comment by mrb** [comment]
@up2go-rsoesemann Invite sent!

**Comment by Up2Go-DavidRenz** [comment]
@mrb I will join you, please send me an invite.

**Comment by adangel** [comment]
You might want to follow with with @rwhogg , as he was the one, who contributed the JSON renderer for code climate (https://github.com/pmd/pmd/pull/83). Maybe he has already a solution?

**Comment by up2go-rsoesemann** [comment]
Thanks for connecting. @rwhogg we were more than happy to find your Code Climate output solution, Would you be interested in joining our effort to provide a pmd code climate engine at [https://github.com/Up2Go/codeclimate-pmd](`https://github.com/Up2Go/codeclimate-pmd`)?

We will start this next week.

We will also have high class support by @mrb and @jpignata of CodeClimate.

**Comment by rwhogg** [comment]
@up2go-rsoesemann thanks for the offer, but no thanks. I already have too many commitments on my plate :)

**Comment by up2go-rsoesemann** [comment]
@rwhogg looking at you r repos I can fully understand that. But thanks anyway for contributing the output formatter for CC.

I guess we need to enhance your code in the next weeks. Just in case we have we have a **few** question now and then can we mention you in our internal issues?

Did you ever create a Code Climate docker image wrapping PMD or what do you build the output formatter for? I'm just wondering if we could learn from what you already did.

**Comment by up2go-rsoesemann** [comment]
@sivakumar-kailasam we have been pointed to your PMD Code Climate engine.
We have just added a new language module to PMD think and planned to provide a Code Climate engine for it. As a next step we want to create a Code Climate engine to make it available there.

I think it would be rather ineffective to provide multiple engines (per language) for PMD but I also want to take over you repo ;-)

Would it be ok if we create a PMD engine ourselves in Java (we have no Groovy skills) or should we join our efforts? We think we need to make enhancements and chances to any existing PMD engine and propose to go the other way around. Learn from you repo built built it in Java instead.

**Comment by sivakumar-kailasam** [comment]
@up2go-rsoesemann I'm working with @mrb in getting the repo up-to-date with the latest code climate spec and also to use the new adapter. I'd love to collaborate with you on my repo. My engine should ideally work with any language repo that pmd supports, but I'd like to hear any other enhancements you might have in mind as an issue over at the existing repo I have so that we can start working towards that. Cheers 😄

**Comment by up2go-rsoesemann** [comment]
@sivakumar-kailasam here are a few things that are of priority to us (and maybe not you):

1. Get the latest release of PMD into the engine (first one including Apex language)
2. Getting upcoming releases of PMD (containing improved rules and those contributed by the Salesforce.com) community into updated engines (= Ongoing support of the PMD engine)
3. Allow the PMD wrapper to recognize all PMD-supported languages in the Code Climate input files and let them be auto recognized by PMDs Command Line. As opposed to multiple PMD engines for a single language.
4. Use the PMD Code Climate output format that is part of PMD (not a handcoded one in the Docker file) and enhance it so it can be customizable by the CodeClimate user via a PMD param.
5. Guarantee that there is only a single spot (namingly an adjusted rulesset.xml) in the users files to adjust all PMD specifics AND the code climate specifics (category, remediation points,..)
6. Reduce the amount of glue code (=engine code, wrapping, connecting and mapping stuff) and build a minimal generic engine, so it will work with nearly any upgrade to PMD without having to adjust the engine.
(7. Get the most of this done in the next 2 month and heavily involve our student intern @Up2Go-DavidRenz as this is part of his bachelor thesis. ;-) )

What do you think? Why not have a Skype chat on Friday to discuss further details altogether?

**Comment by sivakumar-kailasam** [comment]
@up2go-rsoesemann Awesome list. I converted these to github issues at https://github.com/sivakumar-kailasam/codeclimate-pmd/issues. I'll assign each one to myself as I go through those. If your team has the time, you can pick up any of the other issues, drop a note on what you have in your mind so that we're all are on the same page and then work towards getting that done via a PR. Let me know if that works 😄

**Comment by up2go-rsoesemann** [comment]
What about my list items 5) and 6)?

I really think we should not require the people to use PMD's ruleset.xml AND Code Climate config.json for PMD specific configuration and I also would like to think about how to prevent the engine being a bottleneck for future updates.

I guess many people want to improve PMD and its rules but as soon if the engine glue code breaks the functionality PMD ist not going to be used in CodeClimate anymore. That's what I meant by making the engine very generic (e.g. by passing through PMD params to the output).

**Comment by sivakumar-kailasam** [comment]
At this point, I'd like to ship a first version that people can start using and give feedback 😄. You can open issues for 5 and 6 and we can figure out how to make it work.

**Comment by up2go-rsoesemann** [comment]
Great. I totally agree to getting out a 1.0 first and thanks for allowing me to create issues for later.

@mrb I think we can close this as I am convinced that everybody will "win" when we focus everybody's efforts on a single PMD engine for all language.

**Comment by up2go-rsoesemann** [comment]
See ongoing discussion and development efforts here: https://github.com/sivakumar-kailasam/codeclimate-pmd

**Comment by up2go-rsoesemann** [comment]
@sivakumar-kailasam and @mrb I again discussed this with @Up2Go-DavidRenz and decided to work on a seperate Apex-only engine located here https://github.com/Up2Go/codeclimate-apex. 

We agree with Michael, that "marketing-wise" it might be smarter to have language specific engines even if the framework under the hood is the same.

We also totally support your argumentation that there should be no battle who is going to deliver the better PMD engine. Siva started months before us and already has accomplished a lot. The fame for doing this should be all yours. ;-) 

Finally we feel responsible for a few constraints that Siva is not going to take over just because we need them. Those are:

- We want to own and control the full cycle of Salesforce experts adding new rules into PMD and getting them into Code Climate. We don't want the owner of the engine Siva be a bottleneck here.
- Last but not least: this is a university project of David and he needs to be the main contributor to a Code Climate engine. 

With that said, I hope we will tightly work together getting PMD to run on CodeClimate in the next weeks.

**Comment by sivakumar-kailasam** [comment]
I'm doing this only for fun, so that open source java projects can use code climate for free 😄. I'm not sure if you had noticed the custom xml ruleset option that's a part of the engine. This enables you to use this engine with a custom ruleset xml that you and your experts can maintain & update. I have updated sivakumar-kailasam/codeclimate-pmd#5 on reasons for repo access. My project is MIT licensed exactly for the reasons mentioned by you so that anyone can fork and start making changes as they see fit. Cheers 😄

**Comment by adangel** [comment]
About the custom ruleset option - I just want to mention, that this is a really necessary feature, as not all rules fit to all use cases. E.g. the java rules from ruleset controversial are usually not universally applicable (e.g. if you have a project that requires native code, you do not want to enable the rule AvoidUsingNativeCode...). Hence, the users of PMD are encouraged to customize the rules to their need -> http://pmd.github.io/pmd-5.4.1/overview/bestpractices.html
Also, some rules allow configuration of parameters (e.g. how big is a big method?), and this is done in a custom ruleset, too.
I assume, this is not a problem yet for the Apex rules, but the more rules you have, the more you are in the need for customization. Also for adopting PMD into a existing codebase it makes sense, to concentrate on a few rules at the beginning and enable more rules over time.
