### ISSUE TITLE
Inner classes get the same line information as their outer classes

### ISSUE THREAD

**Issue by Up2Go-DavidRenz** [Up2Go/pmd#28]
Inner classes get the same line information as their outer classes, so if the outer class hits the excessive class length limit all inner classes also throw an issue. For example the MetadataService.cls creates round about 700 excessive class length issues.

**Comment by up2go-rsoesemann** [comment]
Fixed by https://github.com/Up2Go/pmd/commit/5e9df4a4468c3001b1ca1c70baee930ab0855535
