### ISSUE TITLE
Allow to use and configure other Code Climate output json parameter

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#31]
Add code to the Code Climat Json outputer contributed in https://github.com/pmd/pmd/pull/83/commits/6d2b268ff61b14bf44bf21a19f0d4ef3ccbb2162 so

1.  We can change `remediation_points` and `category` of each rule issue  from its current default "Style" to something more suitable (e.g. Complexity for Cyclomatic Complexity)

2. Each Code Climate user can override this from his ruleset.xml

I guess for 2. we need to have CC specific params per Apex or PMD rule in general and pass them through.

**Comment by up2go-rsoesemann** [comment]
@adangel Is there a way in PMD to define e.g. an `CodeClimateRule` interface that defines that a `Rule` implementing it must provide some extra details as regular PMD properties? Properties for which we would provide defaults in our rules.xml but each user could change them.

This way we could only need a minimal code change in the CodeClimate renderer to use those values if present.

**Comment by adangel** [comment]
I would hesitate, to add something, that is CodeClimate specific to each rule. However, I think, both properties (remediation_points and category) are general enough, to be useful not only for the CodeClimate renderer but for other renderers, too. Category could be used later during execution, to further filter the rules, that should be executed.

Rules in PMD can have additional properties (PropertyDescriptor etc.) that could be used for this purpose. However, I think, currently, these properties are used to customize how the rules work (e.g. setting threshold when rule violations should be reported). For me, these new properties sound more like the "priority" - something that describes a rule, but not a specific rule. I would need to think this over and what the consequences are, if we would enhance e.g. the Rule interface.

**Comment by up2go-rsoesemann** [comment]
@adangel What do you think of my implementation of Code Climate pass through params as commited in https://github.com/Up2Go/pmd/commit/2da01083069f7b8159c690fbc3d6bf7406a8357d?

If you think this fits the way PMD uses properties I would create a PR next week.

**Comment by up2go-rsoesemann** [comment]
@Up2Go-DavidRenz I also added categories as a Rule Property as I think our rule set name = category solution is not good enough. In Code Climate an issue can have more than one category (which makes sense). Besides that we might also want to stick to the Java ruleset names to make improving and porting other rules easier for outside collaborators. What do you think?

**Comment by Up2Go-DavidRenz** [comment]
Maybe we were to hasty by renaming the rulesets. I like the fact that our rulesets match the categories of Code Climate, but maybe we integrated too much CC stuff into our Apex module. Lets talk about this next week.

**Comment by adangel** [comment]
I'm ok with the proposed solution as a CodeClimateRule interface with a property. You could implement the categories the same way as a property - PMD also supports a StringArray / MultiString property type.
I might refactor it in the (far?) future to have this more deeply integrated into PMD, as I feel, these two properties should be "first-class" rule properties like a rule name.

**Comment by up2go-rsoesemann** [comment]
I added a second property for categories today and will create a pr
tommorow. Too late for the eclipse snapshot?! @adangel

Am Sonntag, 17. April 2016 schrieb Andreas Dangel :
