### ISSUE TITLE
PMD fails to apply StdCyclomaticComplexityRule on triggers

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#38]
reported here https://github.com/pmd/pmd/pull/86#issuecomment-219626436

**Comment by up2go-rsoesemann** [comment]
Facing following exception while executing PMD through Command Line:-

`Exception applying rule StdCyclomaticComplexity on file D:\Nachiket Dev Org\Nachiket New Dev Org Dec 2015\src\triggers\AccountTrigger.trigger, continuing with next rule java.util.EmptyStackException at java.util.Stack.peek(Unknown Source) at net.sourceforge.pmd.lang.apex.rule.complexity.StdCyclomaticComplexityRule.visit(StdCyclomaticComplexityRule.java:124) at net.sourceforge.pmd.lang.apex.ast.ASTMethod.jjtAccept(ASTMethod.java:15) at net.sourceforge.pmd.lang.apex.ast.AbstractApexNode.childrenAccept(AbstractApexNode.java:101) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visit(AbstractApexRule.java:131) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visit(AbstractApexRule.java:517) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visitAll(AbstractApexRule.java:124) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.apply(AbstractApexRule.java:114) at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:215) at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:307) at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:125) at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:146) at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:76) at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:43) at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78) at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:25) at java.util.concurrent.FutureTask.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source) Exception applying rule StdCyclomaticComplexity on file D:\Nachiket Dev Org\Nachiket New Dev Org Dec 2015\src\triggers\CaseTrigger.trigger, continuing with next rule java.util.EmptyStackException at java.util.Stack.peek(Unknown Source) at net.sourceforge.pmd.lang.apex.rule.complexity.StdCyclomaticComplexityRule.visit(StdCyclomaticComplexityRule.java:124) at net.sourceforge.pmd.lang.apex.ast.ASTMethod.jjtAccept(ASTMethod.java:15) at net.sourceforge.pmd.lang.apex.ast.AbstractApexNode.childrenAccept(AbstractApexNode.java:101) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visit(AbstractApexRule.java:131) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visit(AbstractApexRule.java:517) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visitAll(AbstractApexRule.java:124) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.apply(AbstractApexRule.java:114) at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:215) at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:307) at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:125) at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:146) at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:76) at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:43) at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78) at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:25) at java.util.concurrent.FutureTask.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source) Exception applying rule StdCyclomaticComplexity on file D:\Nachiket Dev Org\Nachiket New Dev Org Dec 2015\src\triggers\Test_Share.trigger, continuing with next rule java.util.EmptyStackException at java.util.Stack.peek(Unknown Source) at net.sourceforge.pmd.lang.apex.rule.complexity.StdCyclomaticComplexityRule.visit(StdCyclomaticComplexityRule.java:124) at net.sourceforge.pmd.lang.apex.ast.ASTMethod.jjtAccept(ASTMethod.java:15) at net.sourceforge.pmd.lang.apex.ast.AbstractApexNode.childrenAccept(AbstractApexNode.java:101) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visit(AbstractApexRule.java:131) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visit(AbstractApexRule.java:517) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.visitAll(AbstractApexRule.java:124) at net.sourceforge.pmd.lang.apex.rule.AbstractApexRule.apply(AbstractApexRule.java:114) at net.sourceforge.pmd.lang.rule.AbstractDelegateRule.apply(AbstractDelegateRule.java:215) at net.sourceforge.pmd.RuleSet.apply(RuleSet.java:307) at net.sourceforge.pmd.RuleSets.apply(RuleSets.java:125) at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:146) at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:76) at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:43) at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:78) at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:25) at java.util.concurrent.FutureTask.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source)
`

**Comment by up2go-rsoesemann** [comment]
@Up2Go-DavidRenz what do you think? I think we shouldn't close any issue before the fix is really released. Otherwise the reporter might be confused.

**Comment by up2go-rsoesemann** [comment]
Maybe I have to correct myself. The person who reported this was using a SNAPSHOT Eclipse plugin. Maybe if you committed and pull requested this already to @adangel then there is another SNAPSHOT already we could give to this early user.

What do you think @Up2Go-DavidRenz?

**Comment by Up2Go-DavidRenz** [comment]
No you were right. I just pull requested yesterday and it is not merged yet.
https://github.com/pmd/pmd/pull/92

**Comment by Up2Go-DavidRenz** [comment]
https://github.com/pmd/pmd/pull/92 is merged.
