### ISSUE TITLE
Ruleset not found net.sourceforge.pmd.RuleSetNotFoundException

### ISSUE THREAD

**Issue by nachiket-deshpande** [Up2Go/pmd#42]
Facing following exception when executing PMD through command line.

Ruleset not found net.sourceforge.pmd.RuleSetNotFoundException: Can't find resource 'null' for rule 'apex-bugrisk'. Make sure the resource is a valid file or URL and is on the CLASSPATH

![pmd error](https://cloud.githubusercontent.com/assets/18735171/15885421/b2b9c2a6-2d74-11e6-8afa-1c55b8bdff99.jpg)

Please advise.
Thanks,
Nachiket

**Comment by up2go-rsoesemann** [comment]
@Up2Go-DavidRenz could you please have a look if we sneaked a bug into PMD. If this is a PMD core issue please close this one and ask @nachiket-deshpande to use https://sourceforge.net/p/pmd/bugs/ for general issues.

After that we should deactivate issues on our private fork, what do you think?

**Comment by Up2Go-DavidRenz** [comment]
There are no rulesets `apex-bugrisk`, `apex-clarity` and `apex-compatibility` anymore. I'm not sure why you are using them, just use `-R apex-ruleset`.

**Comment by nachiket-deshpande** [comment]
@Up2Go-DavidRenz Thank You.

it worked now.
