### ISSUE TITLE
How to best manage Apex versions in PMD?

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#8]
This issue is about discussing versioning of Apex in the PMD module. Salesforce.com releases three times a year (currently in version 36) and with each version minor or major things change in the language.

The nice thing is that the parser we use from the Force.com IDE (developed by @vazexqi, @anand13s and others) is updated with every release.

We as initial commiter don't want to take care about building rules for previous language versions but want to have the infrastructure in place so other contributers can add language (and rule) diffs later.

1. **@adangel What do we need to know or decide before we can enable versioning? What is the best existing module to learn and "steal" code from?**

2. **@vazexqi What do you think about enabling versioning? As I understood your previous comments you deliver update parser snapshots every release, which we could bundle with PMD. As version numbers we would use the Salesforce.com notation 35,36...**

**Comment by adangel** [comment]
For java, by default the latest version is selected (java 8). The user can manually select an older version (e.g. java 6) and PMD will fail to parse source code which uses new language features. For java we use the same grammar for all versions - but the parser makes sure to throw an exception for "invalid" code. Not really sure, how useful this feature is in the end - as I guess, you would compile your project first before running PMD - and the compiler would already fail...

The other version option is for the rules (and I think, that's what you need): You can configure a "minimumLanguageVersion" and a "maximumLanguageVersion" for each rule - then the rule would only be applied for specific versions. E.g. the [UseVarargs](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/resources/rulesets/java/design.xml#L1827) rule for java uses this - PMD should only suggest using varargs for Java5 and later. Earlier versions of java don't support this language feature.

You would configure the version of Apex in [ApexLanguageModule](https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ApexLanguageModule.java) - where I've added version "1.0". You'll need to replace it with "35"...

I think, as long as the apex parser/compiler is backwards compatible, you just add another version entry there and that's all. If there is the need for a different parser (or parser option) per version, then have a look at the [JavaLanguageModule](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/JavaLanguageModule.java) where each version has its own language handler.

**Comment by vazexqi** [comment]
I think you can prioritize about making this work first and then worry about versioning later.

When I think of a language, I think of it as being the language syntax and semantics, the runtime and the libraries that come standard. With Salesforce, the language syntax and semantics don't change that often. What changes more frequently are the standard libraries (that you do not analyze) and the runtime (which you don't have access to and you never need to deal with something that low-level).

As @adangel alluded to, the language syntax is backwards compatible. I can't think of a case where we removed support of something syntactic. So, you can always use v35 to parse the older languages (modulo some bugs that we fix).
