### ISSUE TITLE
Make TreeBuilder work on node superclasses

### ISSUE THREAD

**Issue by up2go-rsoesemann** [Up2Go/pmd#9]
@vazexqi @anand13s 

Please see commit https://github.com/Up2Go/pmd/commit/3bf1495cc20cf6bb50075643e87ba624299131c0 where I added the minimal nodes you previously mentioned.

1. As expected they are not enough to parse real world code like https://github.com/financialforcedev/fflib-apex-common/blob/master/fflib/src/classes/fflib_SObjectDomain.cls

**How many node are there in total. I guess I need to add adapter classes for all of them.** Right?

2. **Some of the minimal classes you told me to wrap are not compatible with our Nodes or are interfaces. See screenshot. How to cope with them?**

![problems_minimal_astnodes](https://cloud.githubusercontent.com/assets/8180281/13946136/f5bfe78c-f012-11e5-91ec-59e93c0a7ff1.png)

**Comment by vazexqi** [comment]
1. What are the errors that you are seeing when parsing Financial Force?
1. Could you provide more details on what makes them "incompatible" with the interface you have?

**Comment by up2go-rsoesemann** [comment]
@vazexqi 

1. One exception thrown by our internal adapter here https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java#L154
2. The type ExceptionMethods is not a valid substitute for the bounded parameter <T extends AstNode> of the type AbstractApexNode<T>
3. AdditionalInfo cannot be resolved. Which package is it in?
4. Condition and Query Nodes are interfaces. Should we wrap all of their implementations?

**Comment by up2go-rsoesemann** [comment]
@adangel , @vazexqi I think we need another approach here as the amount of different Node Types is HUGE.  I think instead of littering our code with "stupid" wrapper classes for eached detailed node the Jorje Parser knows we should abstract the adapter code so that it is able to handle Base classes like `apex.jorje.semantic.ast.expression.Expression`.

I'm a bit lost with Javas Generic syntax but something like that should make us more flexible

    package net.sourceforge.pmd.lang.apex.ast;
    import apex.jorje.semantic.ast.expression.Expression;

    public class ASTExpression extends AbstractApexNode<? extends Expression> {
        public ASTExpression(Expression expression) {
		super(expression);
        }
    }

**Comment by adangel** [comment]
I'm not sure about merging the classes like you suggested for the Expression: we would map multiple Apex node types into one type in pmd - we would lose information about what specific expression is used. We would need to add expose this in a different way, e.g.

    public String concreteExpression() { return node.getClass().getSimpleName(); }

But it makes writing rules later on more difficult, if the rule is only interested in one specific type - you would need to filter twice. Not so much a problem for XPath rules (e.g. you would write: `//Expression[@concreteExpression='BindExpression']` - 
but in java:
`node.findDescendantsOfType(ASTExpression.class).filter(n -> "BindExpression".equals(n.concreteExpression()))`

vs. just `node.findDescendantsOfType(ASTBindExpression.class)`.

And later on, the wrappers won't stay "stupid" - e.g. the `getImage()` method is probably the one, that's different for many classes. And e.g. in java, the [IfStatement](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/java/net/sourceforge/pmd/lang/java/ast/ASTIfStatement.java) has implemented a `hasElse()` method (e.g. to be used in a rule via XPath `//IfStatement[@hasElse='true']`) - although in java, the value is determined by the compiler, you could implement it for apex by traversing the tree a bit (e.g. check the next sibling).


It came just to my mind, that there is a different approach that is used by the XML module: There we have already a tree with nodes. However, all the nodes are of type `org.w3c.dom.Node`. Here a dynamic proxy is used, which "wraps" the original nodes. The [XmlNodeInvocationHandler](https://github.com/pmd/pmd/blob/master/pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/XmlNodeInvocationHandler.java) is used in the [parser](https://github.com/pmd/pmd/blob/master/pmd-xml/src/main/java/net/sourceforge/pmd/lang/xml/ast/XmlParser.java#L87-L88).
Not sure, if that would fit. Xml nodes are much simpler - they have attributes and that's it. No other properties.

**Comment by adangel** [comment]
Another possibility, to avoid creating maybe unneeded wrappers is, to return a anonymous class instead of throwing an exception in [ApexTreeBuilder](https://github.com/Up2Go/pmd/blob/master/pmd-apex/src/main/java/net/sourceforge/pmd/lang/apex/ast/ApexTreeBuilder.java#L153):

			    return new AbstractApexNode<T>(node) {
			        public String toString() {
			            return node.getClass().getSimpleName();
			        }
                };
			    
				//throw new IllegalArgumentException(
				//		"There is no Node adapter class registered for the Node class: "
				//				+ node.getClass());

I've overriden the "toString()" method, so that the node has a useful name in the dumpFacade. Not sure, how good it works (e.g. which other methods, you should implement) - but as the other classes don't have any extra methods, it should be ok (the absolute minimum seems to be already in the AbstractApexNode). As soon as you need to implement a specific method like "getImage()", "hasElse()", etc. you need to create a wrapper-class and register it.

**Comment by up2go-rsoesemann** [comment]
We should go with a mixture of what @adangel recommended. Adding as many possible Wrappers as needed to enable easy contributions by others and just resort to an inner class in case of excessive node subclasses.
